title: Andy Potter
description: > # this means to ignore newlines until "baseurl:"
  Andy Potter resume and blog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andy Potter # add your name
author-img: scottish-summery-vibes_s.jpg # add your photo
about-author: I am a web developer focusing on back-end Ruby-on-Rails development. I am always learning. # add description
social-github: drewpotter # add your Github handle
social-instagram: s_aint_andy
social-linkedin: drewpotter # add your Linkedin handle
social-email: andrewpottercv@gmail.com # add your Email address

# Disqus
#discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 24
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
